project:
  type: website
  output-dir: docs

website:
  title: "working paper"
  navbar:
    left:
      - href: paper-data-platforms.html
        text: ""

format:
  elseiver-html:
    toc: true
    toc-depth: 2